### ISSUE TITLE
please fix set lore item.

### ISSUE THREAD

**Issue by Karanztez** [mk7a-mc/ItemSoulBind#27]
Plugin version
ItemSoulBind version 1.4.1
Bind items for a single player's use only
Website: https://github.com/mk7a/ItemSoulBind
Author: mk7a

Spigot Version
Paper 1.18.1

Plugin Configuration

File
Plugins List
https://www.spigotmc.org/resources/%E2%9A%A1-customitemgui-pro-%E2%9C%85-stats-abilities-useful-gui-1-14-1-18-%E2%AD%95.94082/

To Reproduce
I can't use set lore item %soulbind%, I'm playing through the Geyser Bedrock

normal java, register item not working

Expected behavior
I need item register normally.

Screenshots

BEDROCK 
![Screenshot_20220102-181606](https://user-images.githubusercontent.com/45115695/147874181-fd48a303-eda5-403d-8cb3-a5d58f7eaa97.png)

JAVA
![received_646756979813685](https://user-images.githubusercontent.com/45115695/147915976-dc39c30e-2a30-4b7c-b7c6-cc4bb9793307.png)

Config
![Screenshot_20220103-162815](https://user-images.githubusercontent.com/45115695/147916037-25a50d11-63e5-43b8-a0b1-3bdb68f4162f.png)

**Comment by mk7a** [comment]
Does this happen on normal java edition?

**Comment by Karanztez** [comment]
> สิ่งนี้เกิดขึ้นกับ java edition ปกติหรือไม่?

normal java,  register item not working
