### ISSUE TITLE
Compatibility with mmoitems

### ISSUE THREAD

**Issue by 2606140097** [mk7a-mc/ItemSoulBind#38]
**Plugin version**
last version

**Spigot Version**
1.19.4

**Plugin Configuration**
<details>
# 检测到下方物品描述则触发绑定
registerString: "灵魂绑定"

# 特殊绑定-物品有下面的描述的会触发特殊绑定，颜色代码不会被检查，大小写敏感

# 物品被使用时绑定
bindOnUse: true
bouString: "等级:"
#物品被右键时绑定(其实是穿上的动作)
bindOnEquip: true
boeString: "等级:"
#物品被捡起时绑定
bindOnPickup: true
bopString: "等级:"

#是否关闭绑定时的粒子特效和声音
disableEffects: false

#当物品被绑定时提示玩家的信息
# 当前玩家变量:%username%
displayLoreMsg: true
loreMsg: "&5已绑定"

# 是否记录玩家试图与其他人的被绑定的物品进行交互的行为
consoleLogDetection: true

# 是否阻止灵魂绑定方块被放置
preventPlacing: false

# 是否阻止灵魂绑定物品在工作台上使用
preventCraft: false

# 是否阻止灵魂绑定物品附魔
preventEnchant: false

# 是否阻止灵魂绑定物品在铁砧使用
preventAnvil: false

# 当灵魂绑定物品在手上时禁止执行的命令
# 只支持根命令，比如下方是"/auction sell"的根命令 :
blockedCommands:
  - "gmp"
  - "mk"
  - "market"
# =======================
# 信息 | '&'是颜色代码前缀
msgPrefix: "&8[&b灵魂&3绑定&8]&r "
denyMsg: "&9这个物品已经被他人绑定了"
detectedItemMessage: "&c将一个绑定物品绑定给别人的行为已被记录."
detectedItemBroadcast: "企图将一个绑定物品绑定给别人."
noPermissionGeneric: "&c没有权限."
noPermissionBindOthers: "&c你没有权限将物品绑定给别人."
bindSuccess: "&a绑定完成."
bindErrorHeldItem: "你手上必须拿着一个物品."
bindErrorAlreadyBound: "这个物品已经被绑定了."
bindErrorNoSuchPlayer: "玩家不在线."
unbindErrorNotBound: "这个物品没有被绑定."
unbindSuccess: "&a绑定已移除."
inventoryProcessSuccess: "&a该玩家的背包已被处理: "
craftDeny: "&c不能用灵魂绑定物品参与合成."
enchantDeny: "&c不能用灵魂绑定物品参与附魔."
anvilDeny: "&c不能用灵魂绑定物品参与铁砧使用."
foundItems: "&7被别人获得的灵魂绑定物品已经归还给你. 输入&b/returnItems &7获取."
noItems: "你没有物品可以被归还."
specialBindDone: "&a特殊绑定已被应用到该物品."
cmdBlocked: "&c该指令不能在手持灵魂绑定物品时使用."
# ======================

configVersionDoNotModify: 1.4
</details>

**Plugins List**
mmoitems

When the player uses the gem set of mmoitems to the bound weapon, the weapon's lore will be updated and the binding will be invalidated ...

**Comment by mk7a** [comment]
Can you create a video showing you reproducing this issue? 

Removal of the lore should not invalidate the bind as it is actually stored in the item meta. If this plugin modifies the item meta then this isn't something I can fix.

If you are referring to the _bind string_ being removed by this plugin before the bind can take place, there may be a way to prevent this, so I'll need to see the video to investigate.

**Comment by 2606140097** [comment]
The specific operation method is that the player places the bound equipment in the box and then uses the gemsetting of mmoitems, at which point the equipment will be rebound, and the gemsetting is something that any player can do

https://github.com/mk7a-mc/ItemSoulBind/assets/76771673/cd81d6c1-c2eb-4e04-90c7-5e96496cd670

**Comment by mk7a** [comment]
Try to spawn an item already bound with

```/minecraft:give @p diamond_sword{PublicBukkitValues:{"itemsoulbind:soulbinduuid":"PUT-YOUR-UUID-HERE"}}```

and check if it still happens

**Comment by 2606140097** [comment]
Looks like this is a problem with mmoitems, so can I use multiple descriptions as registerStrings

**Comment by mk7a** [comment]
Not sure I understand. Can you confirm what happened when you tried the above command?
