### ISSUE TITLE
After Playerdeath bound item can be picked up by another player

### ISSUE THREAD

**Issue by Drizzt11** [mk7a-mc/ItemSoulBind#43]
**Plugin version**
Get plugin version with /ver ItemSoulBind
1.6.2
**Spigot Version**
Get spigot version with /ver
Paper 1.20.4

**Plugins List**
If you are running other plugins, please provide a list.
Bank
ChatItem
ChatManager
Citizens
CoreProtect
CrazyAuctions
Customcrafting
dtltraders
dungeonsxl
dynmap
essentials
holographicdisplays
interactivebooks
ItemSoulBind
Itemsxl
LuckPerms
mcMMO
Minepacks
MobArena
Mobhunting
multiverse
mypet
mythicmobs
parties
phantomeconomy
quests
Rentit
Residence
Roll
Sentinel
ServerBackup
Commandsigns
TicketManager
UltimateRepairing
Ultramailbox
vault
wirelessredstone
wolfyutils
worldborder
worldedit
worldguard
zhorse
**To Reproduce**
Steps to reproduce the behavior
After player death while wearing the gear. When player respawns he/she can drop gear that is souldbound but can be picked up by another player
**Expected behavior**
Gear should be untradedable or droppable or able to be picked up by any other players.
**Screenshots**
If applicable, add screenshots to help explain your problem e.g. console error stacktrace

**Additional context**

**Plugin Configuration**
```
Paste your plugin config here
```
# When player interacts with an item with the register string in its lore, item will be soul bound to them
registerString: "%soulbind%"
# Group bind string
#   Place permission after this string, terminated by a space or end of line
#   Example: %soulbindgroup%perm which will have permission itemsoulbind.group.perm
groupRegisterString: "%soulbindgroup%"

# SPECIAL BINDS - items with relevant bind string will only be bound in the specified conditions
# Color is ignored when checking for string. Case-sensitive.

# Binds when tool is used: used to break block, sword used to hit entity
bindOnUse: true
bouString: "&9Soul binds on use"
# Binds when armor is equipped through in-hand right click
bindOnEquip: true
boeString: "&9Soul binds on equip"
# Binds when item is picked up
bindOnPickup: true
bopString: "&9Soul binds on pickup"

# Disable soul bind particle+sound effects
disableEffects: false

# Display message in item lore of soul bound item
# Use %username% for player name placeholder
displayLoreMsg: true
loreMsg: "&9Soul bound to %username%"
# Similarly for group binds, using placeholder %group%
displayLoreMsgGroup: true
loreMsgGroup: "&9Soul bound to group %group%"

# Log player detected with item soul bound to another player in console
consoleLogDetection: true

# Prevents placing soul bound blocks
preventPlacing: false

# Prevents crafting with soul bound items
preventCraft: true

# Prevents enchanting with soul bound items
preventEnchant: true

# Prevents anvil use with soul bound items
preventAnvil: true

# Blocks commands when soul bound item is held in hand
# Only provide the first part of the command, e.g. for "/auction sell" :
blockedCommands:
  - "ah"

# =======================
# Messages | use '&' for color codes
msgPrefix: "&8[&bSoul&3Bind&8]&r "
denyMsg: "&9This item is soul bound to another player"
denyMsgGroup: "&9This item is soul bound"
detectedItemMessage: "&cAn item soul bound to another player was removed from your inventory. Event has been logged."
detectedItemMessageGroup: "&cA soul bound item that you do not have access to has been detected in your inventory. Event has been logged."
detectedItemBroadcast: "was detected with an item soul bound to another player."
detectedItemBroadcastGroup: "was detected with a soul bound item they do not have access to."
noPermissionGeneric: "&cInsufficient permissions."
noPermissionBindOthers: "&cInsufficient permissions to bind for other players."
bindSuccess: "&aSoul bind complete."
bindErrorHeldItem: "You must be holding an item in your main hand."
bindErrorAlreadyBound: "This item is already soul bound."
bindErrorNoSuchPlayer: "No such player found online."
bindErrorRemoteNoItem: "Specific target player inventory slot is empty."
unbindErrorNotBound: "Item is not soul bound."
unbindSuccess: "&aSoul bind removed."
inventoryProcessSuccess: "&aProcessed inventory of "
craftDeny: "&cCannot craft with soul bound items."
enchantDeny: "&cCannot enchant soul bound items."
anvilDeny: "&cCannot use anvil on soul bound items."
foundItems: "&7Soul bound items found with another player have been returned to you. Use &b/returnItems &7to get them."
noItems: "You have no items to retrieve."
specialBindDone: "&aSpecial bind applied to item."
cmdBlocked: "&cCannot perform this command on a soul bound item."
# ======================

configVersionDoNotModify: 1.6

**Comment by mk7a** [comment]
Hi,
Old plugin versions are not supported. Update to the latest and test again.   
On Tue, Aug 27, 2024 at 14:24, Drizzt11 ***@***.***&gt; wrote:  Assigned #43 to @mk7a.
